"""
Euler Problem 12: Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

What is the value of the first triangle number to have over 500 divisors?
"""

def count_divisors(n):
    if n == 1:
        return 1
    count = 2  # 1 and n
    i = 2
    while i * i <= n:
        if n % i == 0:
            count += 2
            if i * i == n:
                count -= 1
        i += 1
    return count

def solve():
    n = 1
    triangle = 1
    while True:
        if count_divisors(triangle) > 500:
            return triangle
        n += 1
        triangle += n

answer = solve()
print(f"The first triangle number with over 500 divisors is: {answer}")