# Euler Problem 29
# Consider all integer combinations of a^b for 2 <= a <= 5, 2 <= b <= 5.
# How many distinct terms are in the sequence generated by a^b
# for 2 <= a <= 100, 2 <= b <= 100?

terms = set()
for a in range(2, 101):
    for b in range(2, 101):
        terms.add(a ** b)

print(f"Number of distinct terms: {len(terms)}")